apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.ashish.net`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
